name: CMake

on:
  pull_request:
  push:
    branches:
      - main
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
  # Conan cache environment variables
  CONAN_SYSREQUIRES_MODE: enabled
  CONAN_USER_HOME: "${{ github.workspace }}/conan-cache"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-cache/short"

# Use a bash shell so we can use the same syntax for environment variable
# access regardless of the host operating system
defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-conan-modules
      with:
        path: |
          ${{ env.CONAN_USER_HOME }}
          ~/.cache/pip
        key: ${{ runner.os }}-${{ env.BUILD_TYPE }}-${{ hashFiles('CMakeLists.txt') }}-${{ hashFiles('cmake/Conan.cmake') }}

    - name: Install conan
      run: |
        pip3 install wheel setuptools
        pip3 install conan --upgrade
    - name: Ubuntu - Fix Conan Path
      if: startsWith(matrix.os,'ubuntu')
      run: |
        sudo update-alternatives --install /usr/bin/conan conan /home/runner/.local/bin/conan 10
        sudo update-alternatives --config conan

    - name: Configure CMake
      run: |
        cmake -S . -B ./build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build ./build --config $BUILD_TYPE

    - name: Test
      working-directory: ./build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
